_target_: diffusers.schedulers.DDPMScheduler
num_train_timesteps: 1000
beta_start: 0.0001
beta_end: 0.02
beta_schedule: linear
trained_betas: null
variance_type: fixed_large
clip_sample: false
prediction_type: epsilon
thresholding: false
dynamic_thresholding_ratio: 0.995
clip_sample_range: 1.0
sample_max_value: 1.0
timestep_spacing: trailing
steps_offset: 0
rescale_betas_zero_snr: false