_target_: diffusers.models.UNet2DModel
act_fn: silu
add_attention: true
attention_head_dim: 8
attn_norm_num_groups: null
center_input_sample: false
class_embed_type: null
block_out_channels:
  - 128
  - 128
  - 256
  - 256
  - 512
  - 512
down_block_types:
  - DownBlock2D
  - DownBlock2D
  - DownBlock2D
  - DownBlock2D
  - AttnDownBlock2D
  - DownBlock2D
up_block_types:
  - UpBlock2D
  - AttnUpBlock2D
  - UpBlock2D
  - UpBlock2D
  - UpBlock2D
  - UpBlock2D
downsample_padding: 1
downsample_type: conv
dropout: 0.0
flip_sin_to_cos: true
freq_shift: 0
in_channels: 3
layers_per_block: 2
mid_block_scale_factor: 1
norm_eps: 1.0e-05
norm_num_groups: 32
num_class_embeds: null
num_train_timesteps: null
out_channels: 3
resnet_time_scale_shift: default
sample_size: 32
time_embedding_type: positional
upsample_type: conv