_target_: lightning.pytorch.loggers.WandbLogger
project: "latent_prog_diffusion"
entity: "timohrom"
save_dir: "./logs"
settings:
  _target_: wandb.Settings
  _disable_stats: true
  _disable_meta: true
offline: true
